title: Jon Riggert
logo: /assets/profile.jpeg
description: Husband | Dad | Cloud-Centric System Administrator, focusing on Automation & Project Leadership
show_downloads: false
theme: jekyll-theme-minimal
