title: Jon Riggert
logo: /assets/photo.jpg
description: Husband | Dad | Bringing 15+ technical experience in Electronics, Audio-Visual, System-Cloud Administration, and Project Management.
show_downloads: false
theme: jekyll-theme-minimal
